spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class: com.mysql.cj.jdbc.Driver

server:
  port: 8080

logging:
  config: config/log4j2.yaml