spring:
  jpa:
    hibernate: auto-update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_example
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class: com.mysql.cj.jdbc.Driver

server:
  port: 8080

logging:
  config: log4j2.yaml